### ISSUE TITLE
Alternative to constructor name

### ISSUE THREAD

**Issue by caitp** [joliss/node-quick-temp#6]
We're creating wrapped plugins to support incremental builds in angular2, and quick-temp produces very poor names for these.

In ES6, Function.prototype.name is explicitly configurable per section 9.2.11 --- but in legacy engines (including old V8) this is not necessarily true. So, the temp directory name always looks like `diffing_plugin_wrapper` --- which is not super ideal, and will throw if we try to configure it unless we use a super bleeding edge version of V8/io.js.

As an alternative, it would be really great if there was an optional other way to do this.

I'm picturing something like this:

```js
class DiffingPluginWrapper {
  get pluginName() { return this.pluginClass.name; }
  // ...
}
```

```js
function prettyTmpDirName (obj, prop) {
  function cleanString (s) {
    return underscoreString.underscored(s || '')
      .replace(/[^a-z_]/g, '')
      .replace(/^_+/, '')
  }

  var cleanObjectName = (typeof obj.pluginName === 'string'
      ? obj.pluginName
      : (obj.constructor && obj.constructor.name)) || '';
  if (cleanObjectName) cleanObjectName += '-'
  var cleanPropertyName = cleanString(prop)
  return cleanObjectName + cleanPropertyName + '-XXXXXXXX.tmp'
}
```

**Comment by joliss** [comment]
(Discussion in #7.)

**Comment by joliss** [comment]
Closing along with #7.
