### ISSUE TITLE
re-use hazard

### ISSUE THREAD

**Issue by stefanpenner** [joliss/node-quick-temp#8]
[find-base-dir](https://github.com/joliss/node-quick-temp/blob/master/index.js#L39-L42) can get out of sync with the FS. As it stores the existence of the tmp directory in closure state. Rather then confirming from FS.

Although this works on first runs, the fact that it behaves differently on subsequent runs is unfortunate.

An example:

We are moving more CLI acceptance tests to use the programmatic API, rather then a fresh process:
https://github.com/ember-cli/ember-cli/pull/4963/files 
During this process, arbitrary closure state has given us grief. Although we re-instantiate our state between runs, module state pollution (such as this one) causes grief.

Specifically, we destroy the test tmp during test runs, which requires the node-quick-tmp to be rebuilt. But because it believes to have already done this, it does not try again.

node-quick-temp already stores state on the object it is to create a tmp for, if it also stored this state there. It would not always need to check the FS, but it would also not present the same hazard of today.

**Comment by joliss** [comment]
Ah yes. I'd be happy to take a patch to remedy this.

> node-quick-temp already stores state on the object it is to create a tmp for, if it also stored this state there ...

I think it's tricky to tack it onto the object, but perhaps we can simply not cache the base dir in the  `baseDir` variable. What do you think?

I'm guessing the slowest part of `findBaseDir` is the [`realpathSync`](https://github.com/joliss/node-quick-temp/blob/4931df63033a31ef521db5466bee25beb2ccfd22/index.js#L52) call. I *think* that call can be replaced with `path.join(process.cwd(), 'tmp')` though. Cc @rwjblue, who originally put the `realpathSync` call in d5e122be52cf966db8b53f89f47b02d6f37144c7.
